<?php


namespace Feature\Controllers\API;


class MemberControllerTest extends \TestCase
{
    protected $memberId;
    protected $eventId;
    protected $name;
    protected $last_name;
    protected $email;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->memberId = 5;
        $this->eventId = 1;
        $this->name = "Ivan";
        $this->last_name = "Ivanov";
        $this->email = "ivan".rand(1,100)."@mail.ru";
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testGetAllMember()
    {
        $response = $this->get('/api/v1/getAllMember');

        $response->assertResponseStatus(200);
    }

    public function testGetMember(){
        $response = $this->get("/api/v1/getMember/".$this->memberId);

        $response->assertResponseStatus(200);
    }

    public function testGetFilterMember(){
        $response = $this->get("/api/v1/getFilterMember/".$this->eventId);

        $response->assertResponseStatus(200);
    }



}
